s= set()
n= input("Enter number: ")
s.add(n)
n= input("Enter number: ")
s.add(n)
n= input("Enter number: ")
s.add(n)
n= input("Enter number: ")
s.add(n)
n= input("Enter number: ")
s.add(n)
n= input("Enter number: ")
s.add(n)
n= input("Enter number: ")
s.add(n)

print(s)